### ISSUE TITLE
Add link to the about section

### ISSUE THREAD

**Issue by JackyDFu** [gdibe/berlin-metadata-profile#2]
## Suggestion

It would be beneficial for the general accessibility and reasoning of the metadata profile to provide a direct link to the html pages already deployed by gh-pages. I would suggest to include that link in the about section of this repo. The corresponding link would be:

https://gdibe.github.io/berlin-metadata-profile/

**Comment by JackyDFu** [comment]
See also about section in fork: https://github.com/JackyDFu/berlin-metadata-profile

**Comment by ghost** [comment]
done. thanks for the hint.
