### ISSUE TITLE
Remove connection between service category keyword and GEMET thesaurus

### ISSUE THREAD

**Issue by JackyDFu** [gdibe/berlin-metadata-profile#3]
According to

- AK Metadaten (2022). Version 2.1.1. Architektur der Geodateninfrastruktur Deutschland - Konventionen zu Metadaten. URL: https://www.gdi-de.org/download/AK_Metadaten_Konventionen_zu_Metadaten.pdf

row 33 of "iso.html" has to be fixed, the line of code would be:

https://github.com/gdibe/berlin-metadata-profile/blob/03b9fecbf82d569e891ff11006c9e813ca66ea0a/tables/oeffentlich/iso.html#L471

**Comment by ghost** [comment]
done with https://github.com/gdibe/berlin-metadata-profile/pull/4
